
try{
    pachecoputo
}
catch(error){
    console.log("lo siento ocurrio un error de referencia")
}